<?php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class HRReportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Permissions has been added
        $MainPermission = Permission::create([
            'title' => 'HR Reports',
            'name' => 'Hr_reports_manage',
            'guard_name' => 'web',
            'main_group' => 1,
            'parent_id' => 0,
        ]);
        Permission::insert([
            [
                'title' => 'Reports For Calculating Incentives',
                'name' => 'Hr_reports_reports_for_calculating_incentives',
                'guard_name' => 'web',
                'main_group' => 0,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'parent_id' => $MainPermission->id,
            ],
            [
                'title' => 'Reports For Calculating Incentives Detail',
                'name' => 'Hr_reports_reports_for_calculating_incentives_detail',
                'guard_name' => 'web',
                'main_group' => 0,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'parent_id' => $MainPermission->id,
            ],
            [
                'title' => 'Revenue Generated By Operators (Application User)',
                'name' => 'Hr_reports_revenue_generated_by_operators_application_user',
                'guard_name' => 'web',
                'main_group' => 0,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'parent_id' => $MainPermission->id,
            ],
            [
                'title' => 'Revenue Generated By Consultants (Practitioner)',
                'name' => 'Hr_reports_revenue_generated_by_consultants_practitioner',
                'guard_name' => 'web',
                'main_group' => 0,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
                'parent_id' => $MainPermission->id,
            ],
        ]);

        $role = Role::findOrFail(1);

        // Assign Permission to 'administrator' role
        $role->givePermissionTo('Hr_reports_manage');
        $role->givePermissionTo('Hr_reports_reports_for_calculating_incentives');
        $role->givePermissionTo('Hr_reports_reports_for_calculating_incentives_detail');
        $role->givePermissionTo('Hr_reports_revenue_generated_by_operators_application_user');
        $role->givePermissionTo('Hr_reports_revenue_generated_by_consultants_practitioner');
    }
}
