<?php

return [
    // Consultancy SMS Templates
    'sms_templates' => [
        1 => array(
            'name' => '	On consultancy appointment SMS',
            'content' => '',
            'slug' => 'on-appointment',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        2 => array(
            'name' => '2nd message one day before consultancy appointment at 8PM',
            'content' => '',
            'slug' => 'second-sms',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        3 => array(
            'name' => '3rd reminder 2 hours before consultancy appointment',
            'content' => '',
            'slug' => 'third-sms',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        4 => array(
            'name' => 'Promotion SMS',
            'content' => '',
            'slug' => 'promotion-sms',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
    ],
    // Treatment SMS Templates
    'treatment_sms_templates' => [
        1 => array(
            'name' => '	On treatment appointment SMS',
            'content' => '',
            'slug' => 'treatment-on-appointment',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        2 => array(
            'name' => '2nd message one day before treatment appointment at 8PM',
            'content' => '',
            'slug' => 'treatment-second-sms',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        3 => array(
            'name' => '3rd reminder 2 hours before treatment appointment',
            'content' => '',
            'slug' => 'treatment-third-sms',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
    ],
    // Invoice SMS Templates
    'invoice_sms_templates' => [
        1 => array(
            'name' => '	On Invoice Ringup SMS',
            'content' => '',
            'slug' => 'invoice-ringup',
            'active' => '0',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
    ],
    // Plan SMS Templates
    'plan_sms_templates' => [
        1 => array(
            'name' => '	On Plan Cah Received SMS',
            'content' => '',
            'slug' => 'plan-cash',
            'active' => '0',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
    ],
    // Refund SMS Templates
    'refund_sms_templates' => [
        1 => array(
            'name' => '	On Refund SMS',
            'content' => '',
            'slug' => 'refund-amount',
            'active' => '0',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
    ],

    'virtual_sms_templates' => [
        1 => array(
            'name' => '	On virtual consultancy appointment SMS',
            'content' => '',
            'slug' => 'virtual-on-appointment',
            'active' => '0',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        2 => array(
            'name' => '2nd message one day before virtual consultancy appointment at 8PM',
            'content' => '',
            'slug' => 'virtual-second-sms',
            'active' => '0',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        3 => array(
            'name' => '3rd reminder 2 hours before virtual consultancy appointment',
            'content' => '',
            'slug' => 'virtual-third-sms',
            'active' => '0',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
    ],
    // OTP SMS Templates
    'otp_sms_templates' => [
        1 => array(
            'name' => 'OTP',
            'content' => '',
            'slug' => 'otp',
            'active' => '0',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
    ],

    // Lead Statuses
    'lead_statuses' => array(
        1 => array(
            'id' => 1,
            'parent_id' => 0,
            'sort_no' => 1,
            'name' => 'Open',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        2 => array(
            'id' => 2,
            'parent_id' => 0,
            'sort_no' => 2,
            'name' => 'Contacted',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        3 => array(
            'id' => 3,
            'parent_id' => 0,
            'sort_no' => 3,
            'name' => 'Converted',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        4 => array(
            'id' => 4,
            'parent_id' => 0,
            'sort_no' => 4,
            'name' => 'Not Interested',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
        5 => array(
            'id' => 5,
            'parent_id' => 0,
            'sort_no' => 5,
            'name' => 'Junk',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
            'account_id' => '1',
        ),
    ),

    // Settings
    'settings' => array(
        1 => array(
            'id' => 1,
            'name' => 'Head Office Contact',
            'data' => '(021) 111-232-889',
            'slug' => 'sys-headoffice',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        2 => array(
            'id' => 2,
            'name' => 'Custom Discount Range',
            'data' => '0:100',
            'slug' => 'sys-discounts',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        3 => array(
            'id' => 3,
            'name' => 'Documentation Charges',
            'data' => '1000',
            'slug' => 'sys-documentationcharges',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        4 => array(
            'id' => 4,
            'name' => 'Birthday Promotion DayS Range',
            'data' => '10:10',
            'slug' => 'sys-birthdaypromotion',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        5 => array(
            'id' => 5,
            'name' => 'Finance Editing Days',
            'data' => '3',
            'slug' => 'sys-financeediting',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        6 => array(
            'id' => 6,
            'name' => 'Appointment Rescheduled Counter',
            'data' => '3',
            'slug' => 'sys-appointmentrescheduledcounter',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        7 => array(
            'id' => 7,
            'name' => 'System Listing Mode',
            'data' => 'listing',
            'slug' => 'sys-list-mode',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        8 => array(
            'id' => 8,
            'name' => 'Back Date Appointment',
            'data' => '0',
            'slug' => 'sys-back-date-appointment',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'update_at' => \Carbon\Carbon::now(),
        ),
        9 => array(
            'id' => 9,
            'name' => 'Current SMS Operator',
            'data' => '1',
            'slug' => 'sys-current-sms-operator',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        10 => array(
            'id' => 10,
            'name' => 'Consultancy Invoice With Medical History Form',
            'data' => '1',
            'slug' => 'sys-consultancy-invoice-medical-operator',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        11 => array(
            'id' => 11,
            'name' => 'Virtual Consultancy',
            'data' => '2',
            'slug' => 'sys-virtual-consultancy',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
    ),

    // User Operator Settings
    'user_operator_settings' => array(
        1 => array(
            'id' => 1,
            'operator_name' => 'Telenor Corporate SMS',
            'username' => '923458232889',
            'password' => 'zz4567ffRsa67ffRsa',
            'mask' => '',
            'test_mode' => 1,
            'url' => 'https://telenorcsms.com.pk:27677',
            'string_1' => 'N/A',
            'string_2' => 'N/A',
            'account_id' => '1',
            'operator_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        2 => array(
            'id' => 2,
            'operator_name' => 'Jazz Corporate SMS',
            'username' => '03011156718',
            'password' => 'Muna@muchbad2',
            'mask' => '',
            'test_mode' => 1,
            'url' => 'https://enterprise.jazzcmt.com',
            'string_1' => 'N/A',
            'string_2' => 'N/A',
            'account_id' => '1',
            'operator_id' => '2',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
    ),

    // Settings
    'invoice_statuses' => array(
        1 => array(
            'id' => 1,
            'name' => 'Pending',
            'slug' => 'pending',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        2 => array(
            'id' => 2,
            'name' => 'Invoiced',
            'slug' => 'invoiced',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        3 => array(
            'id' => 3,
            'name' => 'Paid',
            'slug' => 'paid',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        ),
        4 => array(
            'id' => 4,
            'name' => 'Cancelled',
            'slug' => 'cancelled',
            'account_id' => '1',
            'created_at' => \Carbon\Carbon::now(),
            'updated_at' => \Carbon\Carbon::now(),
        )
    ),
];
